const Country = [
  {
    'name': 'Afghanistan',
    'callingCode': '93',
    'flag': 'https://restcountries.eu/data/afg.svg'
  }, {
    'name': 'Åland Islands',
    'callingCode': '358',
    'flag': 'https://restcountries.eu/data/ala.svg'
  }, {
    'name': 'Albania',
    'callingCode': '355',
    'flag': 'https://restcountries.eu/data/alb.svg'
  }, {
    'name': 'Algeria',
    'callingCode': '213',
    'flag': 'https://restcountries.eu/data/dza.svg'
  }, {
    'name': 'American Samoa',
    'callingCode': '1684',
    'flag': 'https://restcountries.eu/data/asm.svg'
  }, {
    'name': 'Andorra',
    'callingCode': '376',
    'flag': 'https://restcountries.eu/data/and.svg'
  }, {
    'name': 'Angola',
    'callingCode': '244',
    'flag': 'https://restcountries.eu/data/ago.svg'
  }, {
    'name': 'Anguilla',
    'callingCode': '1264',
    'flag': 'https://restcountries.eu/data/aia.svg'
  }, {
    'name': 'Antarctica',
    'callingCode': '672',
    'flag': 'https://restcountries.eu/data/ata.svg'
  }, {
    'name': 'Antigua and Barbuda',
    'callingCode': '1268',
    'flag': 'https://restcountries.eu/data/atg.svg'
  }, {
    'name': 'Argentina',
    'callingCode': '54',
    'flag': 'https://restcountries.eu/data/arg.svg'
  }, {
    'name': 'Armenia',
    'callingCode': '374',
    'flag': 'https://restcountries.eu/data/arm.svg'
  }, {
    'name': 'Aruba',
    'callingCode': '297',
    'flag': 'https://restcountries.eu/data/abw.svg'
  }, {
    'name': 'Australia',
    'callingCode': '61',
    'flag': 'https://restcountries.eu/data/aus.svg'
  }, {
    'name': 'Austria',
    'callingCode': '43',
    'flag': 'https://restcountries.eu/data/aut.svg'
  }, {
    'name': 'Azerbaijan',
    'callingCode': '994',
    'flag': 'https://restcountries.eu/data/aze.svg'
  }, {
    'name': 'Bahamas',
    'callingCode': '1242',
    'flag': 'https://restcountries.eu/data/bhs.svg'
  }, {
    'name': 'Bahrain',
    'callingCode': '973',
    'flag': 'https://restcountries.eu/data/bhr.svg'
  }, {
    'name': 'Bangladesh',
    'callingCode': '880',
    'flag': 'https://restcountries.eu/data/bgd.svg'
  }, {
    'name': 'Barbados',
    'callingCode': '1246',
    'flag': 'https://restcountries.eu/data/brb.svg'
  }, {
    'name': 'Belarus',
    'callingCode': '375',
    'flag': 'https://restcountries.eu/data/blr.svg'
  }, {
    'name': 'Belgium',
    'callingCode': '32',
    'flag': 'https://restcountries.eu/data/bel.svg'
  }, {
    'name': 'Belize',
    'callingCode': '501',
    'flag': 'https://restcountries.eu/data/blz.svg'
  }, {
    'name': 'Benin',
    'callingCode': '229',
    'flag': 'https://restcountries.eu/data/ben.svg'
  }, {
    'name': 'Bermuda',
    'callingCode': '1441',
    'flag': 'https://restcountries.eu/data/bmu.svg'
  }, {
    'name': 'Bhutan',
    'callingCode': '975',
    'flag': 'https://restcountries.eu/data/btn.svg'
  }, {
    'name': 'Bolivia (Plurinational State of)',
    'callingCode': '591',
    'flag': 'https://restcountries.eu/data/bol.svg'
  }, {
    'name': 'Bonaire, Sint Eustatius and Saba',
    'callingCode': '5997',
    'flag': 'https://restcountries.eu/data/bes.svg'
  }, {
    'name': 'Bosnia and Herzegovina',
    'callingCode': '387',
    'flag': 'https://restcountries.eu/data/bih.svg'
  }, {
    'name': 'Botswana',
    'callingCode': '267',
    'flag': 'https://restcountries.eu/data/bwa.svg'
  }, {
    'name': 'Bouvet Island',
    'callingCode': '',
    'flag': 'https://restcountries.eu/data/bvt.svg'
  }, {
    'name': 'Brazil',
    'callingCode': '55',
    'flag': 'https://restcountries.eu/data/bra.svg'
  }, {
    'name': 'British Indian Ocean Territory',
    'callingCode': '246',
    'flag': 'https://restcountries.eu/data/iot.svg'
  }, {
    'name': 'Virgin Islands (British)',
    'callingCode': '1284',
    'flag': 'https://restcountries.eu/data/vgb.svg'
  }, {
    'name': 'Virgin Islands (U.S.)',
    'callingCode': '1 340',
    'flag': 'https://restcountries.eu/data/vir.svg'
  }, {
    'name': 'Brunei Darussalam',
    'callingCode': '673',
    'flag': 'https://restcountries.eu/data/brn.svg'
  }, {
    'name': 'Bulgaria',
    'callingCode': '359',
    'flag': 'https://restcountries.eu/data/bgr.svg'
  }, {
    'name': 'Burkina Faso',
    'callingCode': '226',
    'flag': 'https://restcountries.eu/data/bfa.svg'
  }, {
    'name': 'Burundi',
    'callingCode': '257',
    'flag': 'https://restcountries.eu/data/bdi.svg'
  }, {
    'name': 'Cambodia',
    'callingCode': '855',
    'flag': 'https://restcountries.eu/data/khm.svg'
  }, {
    'name': 'Cameroon',
    'callingCode': '237',
    'flag': 'https://restcountries.eu/data/cmr.svg'
  }, {
    'name': 'Canada',
    'callingCode': '1',
    'flag': 'https://restcountries.eu/data/can.svg'
  }, {
    'name': 'Cabo Verde',
    'callingCode': '238',
    'flag': 'https://restcountries.eu/data/cpv.svg'
  }, {
    'name': 'Cayman Islands',
    'callingCode': '1345',
    'flag': 'https://restcountries.eu/data/cym.svg'
  }, {
    'name': 'Central African Republic',
    'callingCode': '236',
    'flag': 'https://restcountries.eu/data/caf.svg'
  }, {
    'name': 'Chad',
    'callingCode': '235',
    'flag': 'https://restcountries.eu/data/tcd.svg'
  }, {
    'name': 'Chile',
    'callingCode': '56',
    'flag': 'https://restcountries.eu/data/chl.svg'
  }, {
    'name': 'China',
    'callingCode': '86',
    'flag': 'https://restcountries.eu/data/chn.svg'
  }, {
    'name': 'Christmas Island',
    'callingCode': '61',
    'flag': 'https://restcountries.eu/data/cxr.svg'
  }, {
    'name': 'Cocos (Keeling) Islands',
    'callingCode': '61',
    'flag': 'https://restcountries.eu/data/cck.svg'
  }, {
    'name': 'Colombia',
    'callingCode': '57',
    'flag': 'https://restcountries.eu/data/col.svg'
  }, {
    'name': 'Comoros',
    'callingCode': '269',
    'flag': 'https://restcountries.eu/data/com.svg'
  }, {
    'name': 'Congo',
    'callingCode': '242',
    'flag': 'https://restcountries.eu/data/cog.svg'
  }, {
    'name': 'Congo (Democratic Republic of the)',
    'callingCode': '243',
    'flag': 'https://restcountries.eu/data/cod.svg'
  }, {
    'name': 'Cook Islands',
    'callingCode': '682',
    'flag': 'https://restcountries.eu/data/cok.svg'
  }, {
    'name': 'Costa Rica',
    'callingCode': '506',
    'flag': 'https://restcountries.eu/data/cri.svg'
  }, {
    'name': 'Croatia',
    'callingCode': '385',
    'flag': 'https://restcountries.eu/data/hrv.svg'
  }, {
    'name': 'Cuba',
    'callingCode': '53',
    'flag': 'https://restcountries.eu/data/cub.svg'
  }, {
    'name': 'Curaçao',
    'callingCode': '599',
    'flag': 'https://restcountries.eu/data/cuw.svg'
  }, {
    'name': 'Cyprus',
    'callingCode': '357',
    'flag': 'https://restcountries.eu/data/cyp.svg'
  }, {
    'name': 'Czech Republic',
    'callingCode': '420',
    'flag': 'https://restcountries.eu/data/cze.svg'
  }, {
    'name': 'Denmark',
    'callingCode': '45',
    'flag': 'https://restcountries.eu/data/dnk.svg'
  }, {
    'name': 'Djibouti',
    'callingCode': '253',
    'flag': 'https://restcountries.eu/data/dji.svg'
  }, {
    'name': 'Dominica',
    'callingCode': '1767',
    'flag': 'https://restcountries.eu/data/dma.svg'
  }, {
    'name': 'Dominican Republic',
    'callingCode': '1809',
    'flag': 'https://restcountries.eu/data/dom.svg'
  }, {
    'name': 'Ecuador',
    'callingCode': '593',
    'flag': 'https://restcountries.eu/data/ecu.svg'
  }, {
    'name': 'Egypt',
    'callingCode': '20',
    'flag': 'https://restcountries.eu/data/egy.svg'
  }, {
    'name': 'El Salvador',
    'callingCode': '503',
    'flag': 'https://restcountries.eu/data/slv.svg'
  }, {
    'name': 'Equatorial Guinea',
    'callingCode': '240',
    'flag': 'https://restcountries.eu/data/gnq.svg'
  }, {
    'name': 'Eritrea',
    'callingCode': '291',
    'flag': 'https://restcountries.eu/data/eri.svg'
  }, {
    'name': 'Estonia',
    'callingCode': '372',
    'flag': 'https://restcountries.eu/data/est.svg'
  }, {
    'name': 'Ethiopia',
    'callingCode': '251',
    'flag': 'https://restcountries.eu/data/eth.svg'
  }, {
    'name': 'Falkland Islands (Malvinas)',
    'callingCode': '500',
    'flag': 'https://restcountries.eu/data/flk.svg'
  }, {
    'name': 'Faroe Islands',
    'callingCode': '298',
    'flag': 'https://restcountries.eu/data/fro.svg'
  }, {
    'name': 'Fiji',
    'callingCode': '679',
    'flag': 'https://restcountries.eu/data/fji.svg'
  }, {
    'name': 'Finland',
    'callingCode': '358',
    'flag': 'https://restcountries.eu/data/fin.svg'
  }, {
    'name': 'France',
    'callingCode': '33',
    'flag': 'https://restcountries.eu/data/fra.svg'
  }, {
    'name': 'French Guiana',
    'callingCode': '594',
    'flag': 'https://restcountries.eu/data/guf.svg'
  }, {
    'name': 'French Polynesia',
    'callingCode': '689',
    'flag': 'https://restcountries.eu/data/pyf.svg'
  }, {
    'name': 'French Southern Territories',
    'callingCode': '',
    'flag': 'https://restcountries.eu/data/atf.svg'
  }, {
    'name': 'Gabon',
    'callingCode': '241',
    'flag': 'https://restcountries.eu/data/gab.svg'
  }, {
    'name': 'Gambia',
    'callingCode': '220',
    'flag': 'https://restcountries.eu/data/gmb.svg'
  }, {
    'name': 'Georgia',
    'callingCode': '995',
    'flag': 'https://restcountries.eu/data/geo.svg'
  }, {
    'name': 'Germany',
    'callingCode': '49',
    'flag': 'https://restcountries.eu/data/deu.svg'
  }, {
    'name': 'Ghana',
    'callingCode': '233',
    'flag': 'https://restcountries.eu/data/gha.svg'
  }, {
    'name': 'Gibraltar',
    'callingCode': '350',
    'flag': 'https://restcountries.eu/data/gib.svg'
  }, {
    'name': 'Greece',
    'callingCode': '30',
    'flag': 'https://restcountries.eu/data/grc.svg'
  }, {
    'name': 'Greenland',
    'callingCode': '299',
    'flag': 'https://restcountries.eu/data/grl.svg'
  }, {
    'name': 'Grenada',
    'callingCode': '1473',
    'flag': 'https://restcountries.eu/data/grd.svg'
  }, {
    'name': 'Guadeloupe',
    'callingCode': '590',
    'flag': 'https://restcountries.eu/data/glp.svg'
  }, {
    'name': 'Guam',
    'callingCode': '1671',
    'flag': 'https://restcountries.eu/data/gum.svg'
  }, {
    'name': 'Guatemala',
    'callingCode': '502',
    'flag': 'https://restcountries.eu/data/gtm.svg'
  }, {
    'name': 'Guernsey',
    'callingCode': '44',
    'flag': 'https://restcountries.eu/data/ggy.svg'
  }, {
    'name': 'Guinea',
    'callingCode': '224',
    'flag': 'https://restcountries.eu/data/gin.svg'
  }, {
    'name': 'Guinea-Bissau',
    'callingCode': '245',
    'flag': 'https://restcountries.eu/data/gnb.svg'
  }, {
    'name': 'Guyana',
    'callingCode': '592',
    'flag': 'https://restcountries.eu/data/guy.svg'
  }, {
    'name': 'Haiti',
    'callingCode': '509',
    'flag': 'https://restcountries.eu/data/hti.svg'
  }, {
    'name': 'Heard Island and McDonald Islands',
    'callingCode': '',
    'flag': 'https://restcountries.eu/data/hmd.svg'
  }, {
    'name': 'Holy See',
    'callingCode': '379',
    'flag': 'https://restcountries.eu/data/vat.svg'
  }, {
    'name': 'Honduras',
    'callingCode': '504',
    'flag': 'https://restcountries.eu/data/hnd.svg'
  }, {
    'name': 'Hong Kong',
    'callingCode': '852',
    'flag': 'https://restcountries.eu/data/hkg.svg'
  }, {
    'name': 'Hungary',
    'callingCode': '36',
    'flag': 'https://restcountries.eu/data/hun.svg'
  }, {
    'name': 'Iceland',
    'callingCode': '354',
    'flag': 'https://restcountries.eu/data/isl.svg'
  }, {
    'name': 'India',
    'callingCode': '91',
    'flag': 'https://restcountries.eu/data/ind.svg'
  }, {
    'name': 'Indonesia',
    'callingCode': '62',
    'flag': 'https://restcountries.eu/data/idn.svg'
  }, {
    'name': "Côte d'Ivoire",
    'callingCode': '225',
    'flag': 'https://restcountries.eu/data/civ.svg'
  }, {
    'name': 'Iran (Islamic Republic of)',
    'callingCode': '98',
    'flag': 'https://restcountries.eu/data/irn.svg'
  }, {
    'name': 'Iraq',
    'callingCode': '964',
    'flag': 'https://restcountries.eu/data/irq.svg'
  }, {
    'name': 'Ireland',
    'callingCode': '353',
    'flag': 'https://restcountries.eu/data/irl.svg'
  }, {
    'name': 'Isle of Man',
    'callingCode': '44',
    'flag': 'https://restcountries.eu/data/imn.svg'
  }, {
    'name': 'Israel',
    'callingCode': '972',
    'flag': 'https://restcountries.eu/data/isr.svg'
  }, {
    'name': 'Italy',
    'callingCode': '39',
    'flag': 'https://restcountries.eu/data/ita.svg'
  }, {
    'name': 'Jamaica',
    'callingCode': '1876',
    'flag': 'https://restcountries.eu/data/jam.svg'
  }, {
    'name': 'Japan',
    'callingCode': '81',
    'flag': 'https://restcountries.eu/data/jpn.svg'
  }, {
    'name': 'Jersey',
    'callingCode': '44',
    'flag': 'https://restcountries.eu/data/jey.svg'
  }, {
    'name': 'Jordan',
    'callingCode': '962',
    'flag': 'https://restcountries.eu/data/jor.svg'
  }, {
    'name': 'Kazakhstan',
    'callingCode': '76',
    'flag': 'https://restcountries.eu/data/kaz.svg'
  }, {
    'name': 'Kenya',
    'callingCode': '254',
    'flag': 'https://restcountries.eu/data/ken.svg'
  }, {
    'name': 'Kiribati',
    'callingCode': '686',
    'flag': 'https://restcountries.eu/data/kir.svg'
  }, {
    'name': 'Kuwait',
    'callingCode': '965',
    'flag': 'https://restcountries.eu/data/kwt.svg'
  }, {
    'name': 'Kyrgyzstan',
    'callingCode': '996',
    'flag': 'https://restcountries.eu/data/kgz.svg'
  }, {
    'name': "Lao People's Democratic Republic",
    'callingCode': '856',
    'flag': 'https://restcountries.eu/data/lao.svg'
  }, {
    'name': 'Latvia',
    'callingCode': '371',
    'flag': 'https://restcountries.eu/data/lva.svg'
  }, {
    'name': 'Lebanon',
    'callingCode': '961',
    'flag': 'https://restcountries.eu/data/lbn.svg'
  }, {
    'name': 'Lesotho',
    'callingCode': '266',
    'flag': 'https://restcountries.eu/data/lso.svg'
  }, {
    'name': 'Liberia',
    'callingCode': '231',
    'flag': 'https://restcountries.eu/data/lbr.svg'
  }, {
    'name': 'Libya',
    'callingCode': '218',
    'flag': 'https://restcountries.eu/data/lby.svg'
  }, {
    'name': 'Liechtenstein',
    'callingCode': '423',
    'flag': 'https://restcountries.eu/data/lie.svg'
  }, {
    'name': 'Lithuania',
    'callingCode': '370',
    'flag': 'https://restcountries.eu/data/ltu.svg'
  }, {
    'name': 'Luxembourg',
    'callingCode': '352',
    'flag': 'https://restcountries.eu/data/lux.svg'
  }, {
    'name': 'Macao',
    'callingCode': '853',
    'flag': 'https://restcountries.eu/data/mac.svg'
  }, {
    'name': 'Macedonia (the former Yugoslav Republic of)',
    'callingCode': '389',
    'flag': 'https://restcountries.eu/data/mkd.svg'
  }, {
    'name': 'Madagascar',
    'callingCode': '261',
    'flag': 'https://restcountries.eu/data/mdg.svg'
  }, {
    'name': 'Malawi',
    'callingCode': '265',
    'flag': 'https://restcountries.eu/data/mwi.svg'
  }, {
    'name': 'Malaysia',
    'callingCode': '60',
    'flag': 'https://restcountries.eu/data/mys.svg'
  }, {
    'name': 'Maldives',
    'callingCode': '960',
    'flag': 'https://restcountries.eu/data/mdv.svg'
  }, {
    'name': 'Mali',
    'callingCode': '223',
    'flag': 'https://restcountries.eu/data/mli.svg'
  }, {
    'name': 'Malta',
    'callingCode': '356',
    'flag': 'https://restcountries.eu/data/mlt.svg'
  }, {
    'name': 'Marshall Islands',
    'callingCode': '692',
    'flag': 'https://restcountries.eu/data/mhl.svg'
  }, {
    'name': 'Martinique',
    'callingCode': '596',
    'flag': 'https://restcountries.eu/data/mtq.svg'
  }, {
    'name': 'Mauritania',
    'callingCode': '222',
    'flag': 'https://restcountries.eu/data/mrt.svg'
  }, {
    'name': 'Mauritius',
    'callingCode': '230',
    'flag': 'https://restcountries.eu/data/mus.svg'
  }, {
    'name': 'Mayotte',
    'callingCode': '262',
    'flag': 'https://restcountries.eu/data/myt.svg'
  }, {
    'name': 'Mexico',
    'callingCode': '52',
    'flag': 'https://restcountries.eu/data/mex.svg'
  }, {
    'name': 'Micronesia (Federated States of)',
    'callingCode': '691',
    'flag': 'https://restcountries.eu/data/fsm.svg'
  }, {
    'name': 'Moldova (Republic of)',
    'callingCode': '373',
    'flag': 'https://restcountries.eu/data/mda.svg'
  }, {
    'name': 'Monaco',
    'callingCode': '377',
    'flag': 'https://restcountries.eu/data/mco.svg'
  }, {
    'name': 'Mongolia',
    'callingCode': '976',
    'flag': 'https://restcountries.eu/data/mng.svg'
  }, {
    'name': 'Montenegro',
    'callingCode': '382',
    'flag': 'https://restcountries.eu/data/mne.svg'
  }, {
    'name': 'Montserrat',
    'callingCode': '1664',
    'flag': 'https://restcountries.eu/data/msr.svg'
  }, {
    'name': 'Morocco',
    'callingCode': '212',
    'flag': 'https://restcountries.eu/data/mar.svg'
  }, {
    'name': 'Mozambique',
    'callingCode': '258',
    'flag': 'https://restcountries.eu/data/moz.svg'
  }, {
    'name': 'Myanmar',
    'callingCode': '95',
    'flag': 'https://restcountries.eu/data/mmr.svg'
  }, {
    'name': 'Namibia',
    'callingCode': '264',
    'flag': 'https://restcountries.eu/data/nam.svg'
  }, {
    'name': 'Nauru',
    'callingCode': '674',
    'flag': 'https://restcountries.eu/data/nru.svg'
  }, {
    'name': 'Nepal',
    'callingCode': '977',
    'flag': 'https://restcountries.eu/data/npl.svg'
  }, {
    'name': 'Netherlands',
    'callingCode': '31',
    'flag': 'https://restcountries.eu/data/nld.svg'
  }, {
    'name': 'New Caledonia',
    'callingCode': '687',
    'flag': 'https://restcountries.eu/data/ncl.svg'
  }, {
    'name': 'New Zealand',
    'callingCode': '64',
    'flag': 'https://restcountries.eu/data/nzl.svg'
  }, {
    'name': 'Nicaragua',
    'callingCode': '505',
    'flag': 'https://restcountries.eu/data/nic.svg'
  }, {
    'name': 'Niger',
    'callingCode': '227',
    'flag': 'https://restcountries.eu/data/ner.svg'
  }, {
    'name': 'Nigeria',
    'callingCode': '234',
    'flag': 'https://restcountries.eu/data/nga.svg'
  }, {
    'name': 'Niue',
    'callingCode': '683',
    'flag': 'https://restcountries.eu/data/niu.svg'
  }, {
    'name': 'Norfolk Island',
    'callingCode': '672',
    'flag': 'https://restcountries.eu/data/nfk.svg'
  }, {
    'name': "Korea (Democratic People's Republic of)",
    'callingCode': '850',
    'flag': 'https://restcountries.eu/data/prk.svg'
  }, {
    'name': 'Northern Mariana Islands',
    'callingCode': '1670',
    'flag': 'https://restcountries.eu/data/mnp.svg'
  }, {
    'name': 'Norway',
    'callingCode': '47',
    'flag': 'https://restcountries.eu/data/nor.svg'
  }, {
    'name': 'Oman',
    'callingCode': '968',
    'flag': 'https://restcountries.eu/data/omn.svg'
  }, {
    'name': 'Pakistan',
    'callingCode': '92',
    'flag': 'https://restcountries.eu/data/pak.svg'
  }, {
    'name': 'Palau',
    'callingCode': '680',
    'flag': 'https://restcountries.eu/data/plw.svg'
  }, {
    'name': 'Palestine, State of',
    'callingCode': '970',
    'flag': 'https://restcountries.eu/data/pse.svg'
  }, {
    'name': 'Panama',
    'callingCode': '507',
    'flag': 'https://restcountries.eu/data/pan.svg'
  }, {
    'name': 'Papua New Guinea',
    'callingCode': '675',
    'flag': 'https://restcountries.eu/data/png.svg'
  }, {
    'name': 'Paraguay',
    'callingCode': '595',
    'flag': 'https://restcountries.eu/data/pry.svg'
  }, {
    'name': 'Peru',
    'callingCode': '51',
    'flag': 'https://restcountries.eu/data/per.svg'
  }, {
    'name': 'Philippines',
    'callingCode': '63',
    'flag': 'https://restcountries.eu/data/phl.svg'
  }, {
    'name': 'Pitcairn',
    'callingCode': '64',
    'flag': 'https://restcountries.eu/data/pcn.svg'
  }, {
    'name': 'Poland',
    'callingCode': '48',
    'flag': 'https://restcountries.eu/data/pol.svg'
  }, {
    'name': 'Portugal',
    'callingCode': '351',
    'flag': 'https://restcountries.eu/data/prt.svg'
  }, {
    'name': 'Puerto Rico',
    'callingCode': '1787',
    'flag': 'https://restcountries.eu/data/pri.svg'
  }, {
    'name': 'Qatar',
    'callingCode': '974',
    'flag': 'https://restcountries.eu/data/qat.svg'
  }, {
    'name': 'Republic of Kosovo',
    'callingCode': '383',
    'flag': 'https://restcountries.eu/data/kos.svg'
  }, {
    'name': 'Réunion',
    'callingCode': '262',
    'flag': 'https://restcountries.eu/data/reu.svg'
  }, {
    'name': 'Romania',
    'callingCode': '40',
    'flag': 'https://restcountries.eu/data/rou.svg'
  }, {
    'name': 'Russian Federation',
    'callingCode': '7',
    'flag': 'https://restcountries.eu/data/rus.svg'
  }, {
    'name': 'Rwanda',
    'callingCode': '250',
    'flag': 'https://restcountries.eu/data/rwa.svg'
  }, {
    'name': 'Saint Barthélemy',
    'callingCode': '590',
    'flag': 'https://restcountries.eu/data/blm.svg'
  }, {
    'name': 'Saint Helena, Ascension and Tristan da Cunha',
    'callingCode': '290',
    'flag': 'https://restcountries.eu/data/shn.svg'
  }, {
    'name': 'Saint Kitts and Nevis',
    'callingCode': '1869',
    'flag': 'https://restcountries.eu/data/kna.svg'
  }, {
    'name': 'Saint Lucia',
    'callingCode': '1758',
    'flag': 'https://restcountries.eu/data/lca.svg'
  }, {
    'name': 'Saint Martin (French part)',
    'callingCode': '590',
    'flag': 'https://restcountries.eu/data/maf.svg'
  }, {
    'name': 'Saint Pierre and Miquelon',
    'callingCode': '508',
    'flag': 'https://restcountries.eu/data/spm.svg'
  }, {
    'name': 'Saint Vincent and the Grenadines',
    'callingCode': '1784',
    'flag': 'https://restcountries.eu/data/vct.svg'
  }, {
    'name': 'Samoa',
    'callingCode': '685',
    'flag': 'https://restcountries.eu/data/wsm.svg'
  }, {
    'name': 'San Marino',
    'callingCode': '378',
    'flag': 'https://restcountries.eu/data/smr.svg'
  }, {
    'name': 'Sao Tome and Principe',
    'callingCode': '239',
    'flag': 'https://restcountries.eu/data/stp.svg'
  }, {
    'name': 'Saudi Arabia',
    'callingCode': '966',
    'flag': 'https://restcountries.eu/data/sau.svg'
  }, {
    'name': 'Senegal',
    'callingCode': '221',
    'flag': 'https://restcountries.eu/data/sen.svg'
  }, {
    'name': 'Serbia',
    'callingCode': '381',
    'flag': 'https://restcountries.eu/data/srb.svg'
  }, {
    'name': 'Seychelles',
    'callingCode': '248',
    'flag': 'https://restcountries.eu/data/syc.svg'
  }, {
    'name': 'Sierra Leone',
    'callingCode': '232',
    'flag': 'https://restcountries.eu/data/sle.svg'
  }, {
    'name': 'Singapore',
    'callingCode': '65',
    'flag': 'https://restcountries.eu/data/sgp.svg'
  }, {
    'name': 'Sint Maarten (Dutch part)',
    'callingCode': '1721',
    'flag': 'https://restcountries.eu/data/sxm.svg'
  }, {
    'name': 'Slovakia',
    'callingCode': '421',
    'flag': 'https://restcountries.eu/data/svk.svg'
  }, {
    'name': 'Slovenia',
    'callingCode': '386',
    'flag': 'https://restcountries.eu/data/svn.svg'
  }, {
    'name': 'Solomon Islands',
    'callingCode': '677',
    'flag': 'https://restcountries.eu/data/slb.svg'
  }, {
    'name': 'Somalia',
    'callingCode': '252',
    'flag': 'https://restcountries.eu/data/som.svg'
  }, {
    'name': 'South Africa',
    'callingCode': '27',
    'flag': 'https://restcountries.eu/data/zaf.svg'
  }, {
    'name': 'South Georgia and the South Sandwich Islands',
    'callingCode': '500',
    'flag': 'https://restcountries.eu/data/sgs.svg'
  }, {
    'name': 'Korea (Republic of)',
    'callingCode': '82',
    'flag': 'https://restcountries.eu/data/kor.svg'
  }, {
    'name': 'South Sudan',
    'callingCode': '211',
    'flag': 'https://restcountries.eu/data/ssd.svg'
  }, {
    'name': 'Spain',
    'callingCode': '34',
    'flag': 'https://restcountries.eu/data/esp.svg'
  }, {
    'name': 'Sri Lanka',
    'callingCode': '94',
    'flag': 'https://restcountries.eu/data/lka.svg'
  }, {
    'name': 'Sudan',
    'callingCode': '249',
    'flag': 'https://restcountries.eu/data/sdn.svg'
  }, {
    'name': 'Suriname',
    'callingCode': '597',
    'flag': 'https://restcountries.eu/data/sur.svg'
  }, {
    'name': 'Svalbard and Jan Mayen',
    'callingCode': '4779',
    'flag': 'https://restcountries.eu/data/sjm.svg'
  }, {
    'name': 'Swaziland',
    'callingCode': '268',
    'flag': 'https://restcountries.eu/data/swz.svg'
  }, {
    'name': 'Sweden',
    'callingCode': '46',
    'flag': 'https://restcountries.eu/data/swe.svg'
  }, {
    'name': 'Switzerland',
    'callingCode': '41',
    'flag': 'https://restcountries.eu/data/che.svg'
  }, {
    'name': 'Syrian Arab Republic',
    'callingCode': '963',
    'flag': 'https://restcountries.eu/data/syr.svg'
  }, {
    'name': 'Taiwan',
    'callingCode': '886',
    'flag': 'https://restcountries.eu/data/twn.svg'
  }, {
    'name': 'Tajikistan',
    'callingCode': '992',
    'flag': 'https://restcountries.eu/data/tjk.svg'
  }, {
    'name': 'Tanzania, United Republic of',
    'callingCode': '255',
    'flag': 'https://restcountries.eu/data/tza.svg'
  }, {
    'name': 'Thailand',
    'callingCode': '66',
    'flag': 'https://restcountries.eu/data/tha.svg'
  }, {
    'name': 'Timor-Leste',
    'callingCode': '670',
    'flag': 'https://restcountries.eu/data/tls.svg'
  }, {
    'name': 'Togo',
    'callingCode': '228',
    'flag': 'https://restcountries.eu/data/tgo.svg'
  }, {
    'name': 'Tokelau',
    'callingCode': '690',
    'flag': 'https://restcountries.eu/data/tkl.svg'
  }, {
    'name': 'Tonga',
    'callingCode': '676',
    'flag': 'https://restcountries.eu/data/ton.svg'
  }, {
    'name': 'Trinidad and Tobago',
    'callingCode': '1868',
    'flag': 'https://restcountries.eu/data/tto.svg'
  }, {
    'name': 'Tunisia',
    'callingCode': '216',
    'flag': 'https://restcountries.eu/data/tun.svg'
  }, {
    'name': 'Turkey',
    'callingCode': '90',
    'flag': 'https://restcountries.eu/data/tur.svg'
  }, {
    'name': 'Turkmenistan',
    'callingCode': '993',
    'flag': 'https://restcountries.eu/data/tkm.svg'
  }, {
    'name': 'Turks and Caicos Islands',
    'callingCode': '1649',
    'flag': 'https://restcountries.eu/data/tca.svg'
  }, {
    'name': 'Tuvalu',
    'callingCode': '688',
    'flag': 'https://restcountries.eu/data/tuv.svg'
  }, {
    'name': 'Uganda',
    'callingCode': '256',
    'flag': 'https://restcountries.eu/data/uga.svg'
  }, {
    'name': 'Ukraine',
    'callingCode': '380',
    'flag': 'https://restcountries.eu/data/ukr.svg'
  }, {
    'name': 'United Arab Emirates',
    'callingCode': '971',
    'flag': 'https://restcountries.eu/data/are.svg'
  }, {
    'name': 'United Kingdom of Great Britain and Northern Ireland',
    'callingCode': '44',
    'flag': 'https://restcountries.eu/data/gbr.svg'
  }, {
    'name': 'United States of America',
    'callingCode': '+1',
    'flag': 'https://restcountries.eu/data/usa.svg'
  }, {
    'name': 'Uruguay',
    'callingCode': '598',
    'flag': 'https://restcountries.eu/data/ury.svg'
  }, {
    'name': 'Uzbekistan',
    'callingCode': '998',
    'flag': 'https://restcountries.eu/data/uzb.svg'
  }, {
    'name': 'Vanuatu',
    'callingCode': '678',
    'flag': 'https://restcountries.eu/data/vut.svg'
  }, {
    'name': 'Venezuela (Bolivarian Republic of)',
    'callingCode': '58',
    'flag': 'https://restcountries.eu/data/ven.svg'
  }, {
    'name': 'Viet Nam',
    'callingCode': '84',
    'flag': 'https://restcountries.eu/data/vnm.svg'
  }, {
    'name': 'Wallis and Futuna',
    'callingCode': '681',
    'flag': 'https://restcountries.eu/data/wlf.svg'
  }, {
    'name': 'Western Sahara',
    'callingCode': '212',
    'flag': 'https://restcountries.eu/data/esh.svg'
  }, {
    'name': 'Yemen',
    'callingCode': '967',
    'flag': 'https://restcountries.eu/data/yem.svg'
  }, {
    'name': 'Zambia',
    'callingCode': '260',
    'flag': 'https://restcountries.eu/data/zmb.svg'
  }, {
    'name': 'Zimbabwe',
    'callingCode': '263',
    'flag': 'https://restcountries.eu/data/zwe.svg'
  }];

export default Country;
